# Store URLs, API endpoints, and file names# config.yaml
project_name: "osteosarcoma_proteomics_ml"

# Directory Structure (Python will use this to ensure folders exist)
directories:
  raw_data: "data/raw"
  mapped_data: "data/mapped"
  processed_data: "data/processed"
  logs: "logs"

# Primary Data Sources(proteomics, genomic and proteomic data sets to be added later)
datasets:
  source: "https://www.mdpi.com/2073-4409/12/17/2179"
  supplementary: "https://www.mdpi.com/article/10.3390/cells12172179/s1"
  supplementary_zip: "cells-12-02179-s001"
  tables:
    patient_info: "Table S1-Patient information and follow-up data.xlsx"
    protein_data: "Table S2-Proteins identified in proteomics analysis.csv"
  
  zhang_chemoresponse:
  # Chemo-Resistant Hub Proteins
    source: "https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2025.1597750/full"
    doi: "10.3389/fonc.2025.1597750"
    local_path: "data/raw/EV3.xlsx"
    local_path: "data/raw/table1.xlsx"

  lee_phospho_drug:
  # Note: these are from cell lines not patient tumor samples
    source: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10883282/"
    doi: "10.1038/s44320-023-00004-7"
    files:
      # Drug response metrics(EV3). Total protein abundance(EV4). Phosphorylation state(EV5).
      drug_response: "data/raw/EV3.xlsx"
      protein_abundance: "data/raw/EV4.xlsx"
      phospho: "data/raw/EV5.csv"

  depmap_broad:
  # Drug Sensitivity Benchmarks (Ready)
  # Note: these are from cell lines not patient tumor samples
    source: "https://depmap.org/portal/data_page/?tab=allData"
    local_path: "data/raw/GDSC2AUCMatrix.csv"