# Store URLs, API endpoints, and file names# config.yaml
project_name: "osteosarcoma_proteomics_ml"

# Directory Structure (Python will use this to ensure folders exist)
directories:
  raw_data: "data/raw"
  mapped_data: "data/mapped"
  processed_data: "data/processed"
  logs: "logs"

# Primary Data Sources(proteomics, genomic and proteomic data sets to be added later)
datasets:
  MassIVE:
  # Proteomics Discovery Data
    # Need to download all files under search tab and merge
    source: "https://www.mdpi.com/2073-4409/12/17/2179"
    project_accession: "MSV000091434"
    ftp_link: "ftp://massive-ftp.ucsd.edu/v05/MSV000091434/"
    target_extensions: [".txt", ".tsv", ".mzTab"] 
    
  zhang_chemoresponse:
  # Chemo-Resistant Hub Proteins (Ready)
    source: "https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2025.1597750/full"
    doi: "10.3389/fonc.2025.1597750"
    local_path: "data/raw/EV3.xlsx"
    
  lee_phospho_drug:
  # Ready
    source: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10883282/#Sec2"
    doi: "10.1038/s44320-023-00004-7"
    files:
      # Drug response metrics(EV3). Total protein abundance(EV4). Phosphorylation state(EV5).
      local_path: "data/raw/EV3.xlsx"
      local_path: "data/raw/EV4.xlsx"
      local_path: "data/raw/EV5.csv"

  depmap_broad:
  # Drug Sensitivity Benchmarks (Ready)
    source: "https://depmap.org/portal/data_page/?tab=allData"
    local_path: "data/raw/GDSC2AUCMatrix.csv"